name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2

    - name : Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '18'
        
    - name: Display package.json
      working-directory: culinary-canvas/capstone-project/backend
      run: cat package.json

    - name: Generate Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npx prisma generate
      
    - name: Install backend dependencies
      working-directory: culinary-canvas/capstone-project/backend
      run: npm install

    - name: Install frontend dependencies
      working-directory: culinary-canvas/capstone-project/frontend/my_capstone_project
      run: npm ci
      
    - name: Start backend server
      working-directory: culinary-canvas/capstone-project/backend
      run: |
        node index.js &
        echo $! > backend_pid.txt
        sleep 15
        
    - name: Test get recipes
      env:
        AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
        
      run: |
        node -e "
        const http = require('http');
        const options = {
          hostname: '127.0.0.1',
          port: 3000,
          path: '/recipes',
          method: 'GET',
          headers: {
            'Authorization': 'Bearer ' + process.env.AUTH_TOKEN
          }
        };
        const req = http.request(options, (res) => {
          console.log('Status Code: ', res.statusCode);
          res.setEncoding('utf8');
          res.on('data', (chunk) => {
            console.log('Response: '+ chunk);
          });
          res.on('end', () => {
            if (res.statusCode === 200){
              console.log('Backend is running correctly')
              process.exit(0)
            } else{
              console.log('Backend is not running correctly. Status: ', res.statusCode);
            };
          });
        });
        req.on('error', (error) => {
          console.error('Error: ', error);
          process.exit(1);
        });
        req.end();"

    - name : Check installed packages
      working-directory: culinary-canvas/capstone-project/backend
      run: npm list @prisma/client

    - name : Install Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npm install @prisma/client
      
    - name : Generate Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npx prisma generate

    - name: Test web scraping flow
      env:
        TEST_URL: ${{secrets.TEST_URL}}
        USER_ID: ${{secrets.USER_ID}}
      run : |
        node -e "
        const http = require('http');
        const options = {
          hostname : 'localhost',
          port: 3000,
          path: '/scrape-recipe',
          method: 'POST',
          headers: {
            'Content-Type' : 'application/json'
          }
        };
        const req = http.request(options, (res) => {
        if (res.statusCode === 200){
          console.log('Web scraping flow is working correctly');
          process.exit(0);
        }else{
          console.log('Web scraping flow is not working correctly');
          console.log('Status Code: ', res.statusCode);
          process.exit(1)
        }
        });
        req.on('error', (error) => {
          console.error('Error: ', error);
          process.exit(1)
        });
        req.write(JSON.stringify({
           url: process.env.TEST_URL,
           userId: process.env.USER_ID
        }));
        req.end();"

    - name: Build frontend
      working-directory: culinary-canvas/capstone-project/frontend/my_capstone_project
      run: npm run build
