name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '18'

    - name: Check Backend Formatting
      working-directory: culinary-canvas/capstone-project/backend
      run: |
        npm install
        npx prettier --write .

    - name: Check Frontend Formatting
      working-directory: culinary-canvas/capstone-project/frontend/my_capstone_project
      run: |
        npm install
        npx prettier --write .
      
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses : actions/checkout@v2

    - name : Set up Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '18'
        
    - name: Display package.json
      working-directory: culinary-canvas/capstone-project/backend
      run: cat package.json

    - name: Generate Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npx prisma generate
      
    - name: Install backend dependencies
      working-directory: culinary-canvas/capstone-project/backend
      run: npm install

    - name: Install frontend dependencies
      working-directory: culinary-canvas/capstone-project/frontend/my_capstone_project
      run: npm ci

    - name: Build frontend
      working-directory: culinary-canvas/capstone-project/frontend/my_capstone_project
      run: npm run build
      
    - name: Start backend server
      working-directory: culinary-canvas/capstone-project/backend
      env:
        DATABASE_URL : ${{secrets.DATABASE_URL}}
        SECRET_KEY: ${{secrets.JWT_SECRET_TOKEN}}
        PRIVATE_VAPID_KEY: ${{ secrets.PRIVATE_VAPID_KEY }}
        PUBLIC_VAPID_KEY: ${{ secrets.PUBLIC_VAPID_KEY }}
      run: |
        node index.js &
        echo $! > backend_pid.txt
        sleep 15
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with: 
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install flake8 mypy
        if [ -f culinary-canvas/capstone-project/backend/requirements.txt ]; then pip3 install -r culinary-canvas/capstone-project/backend/requirements.txt; fi

    - name: Run Flake8
      working-directory: culinary-canvas/capstone-project/backend
      run: python3 -m flake8 webScraper.py

    - name: Run mypy
      working-directory: culinary-canvas/capstone-project/backend
      run: python3 -m mypy webScraper.py

    - name : Check installed packages
      working-directory: culinary-canvas/capstone-project/backend
      run: npm list @prisma/client

    - name : Install Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npm install @prisma/client
      
    - name : Generate Prisma Client
      working-directory: culinary-canvas/capstone-project/backend
      run: npx prisma generate

    - name: Install node-fetch
      run: npm install node-fetch

    - name: Test Python script
      working-directory: culinary-canvas/capstone-project/backend
      run: |
        python3 webScraper.py "${{secrets.TEST_URL}}"

    - name: Test get recipes
      env:
        AUTH_TOKEN: ${{secrets.AUTH_TOKEN}}
        
      run: |
        node -e "
        const http = require('http');
        const options = {
          hostname: '127.0.0.1',
          port: 3000,
          path: '/recipes',
          method: 'GET',
          headers: {
            'Authorization': 'Bearer ' + process.env.AUTH_TOKEN
          }
        };
        const req = http.request(options, (res) => {
          res.setEncoding('utf8');
          res.on('data', (chunk) => {
            console.log('Response: '+ chunk);
          });
          res.on('end', () => {
            if (res.statusCode === 200){
              console.log('Backend is running correctly')
              process.exit(0)
            } else{
              console.log('Backend is not running correctly. Status: ', res.statusCode);
            };
          });
        });
        req.on('error', (error) => {
          console.error('Error: ', error);
          process.exit(1);
        });
        req.end();"


    - name: Test web scraping flow
      env:
        TEST_URL: "${{secrets.TEST_URL}}"
        USER_ID: ${{secrets.USER_ID}}
      run : |
        node -e "
        const http = require('http');
        const options = {
          hostname : '127.0.0.1',
          port: 3000,
          path: '/scrape-recipe',
          method: 'POST',
          headers: {
            'Content-Type' : 'application/json'
          }
        };
        const req = http.request(options, (res) => {
          res.setEncoding('utf8');
          res.on('data', (chunk) => {
            console.log('Response: '+ chunk);
          });
          res.on('end', () => {
            if (res.statusCode === 200){
              console.log('Web scraping flow is working correctly');
              process.exit(0);
            }else{
              console.log('Web scraping flow is not working correctly');
              console.log('Status Code: ', res.statusCode);
            }
          });
        });
        req.on('error', (error) => {
          console.error('Error: ', error);
          process.exit(1)
        });
        const postData = JSON.stringify({
           url: process.env.TEST_URL,
           userId: parseInt(process.env.USER_ID, 10)
        });
        console.log('Sending request with data: ', postData);
        req.write(postData);
        req.end();"
  
